name: Lint

on: 
    push:
        branches: main

jobs: 
    lint-format:
        runs-on: ubuntu-latest

        steps: 
            - name: Checkout Repository
              uses: actions/checkout@v7

            - name: Install Foundry
              uses: foundry-rs/foundry-toolchain@v1
            
            - name: Lint Solidity Code
              run: forge fmt --check
